name: build

on:
  [push, pull_request]

jobs:
  build:
    name: "ci"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: "pull docker image"
        run: docker pull hobywan/cosyr:latest

      - name: "create volume, build cosyr and run test"
        run: |
          docker run -v "$(pwd):/home/cosyr" hobywan/cosyr /bin/bash -c \
            "cd /home/cosyr && mkdir build && cd build && \
            cmake -Wno-dev \
              -DCMAKE_BUILD_TYPE=Release \
              -DENABLE_TCMALLOC=False \
              -DPORTAGE_DIR=/home/dependencies/portage \
              -DKokkos_DIR=/home/dependencies/kokkos \
              -Dpybind11_DIR=/home/dependencies/pybind \
              -DCabana_DIR=/home/dependencies/cabana \
              .. && \
            make -j 4 && \
            export PYTHONPATH=/home/cosyr && \
            export OMP_PROC_BIND=close and OMP_PLACES=cores && \
            mpiexec -np 1 ./cosyr /home/cosyr/input/test_beam_g10_l200.py && \
            cmp /home/cosyr/build/test_beam_g10_l200/mesh/399/comoving_mesh_field.csv \
                /home/cosyr/analysis/reference_field.csv"